### ISSUE TITLE
How is serverless.js used?

### ISSUE THREAD

**Issue by iDVB** [blackflux/lambda-monitor#355]
Great Services btw! this is exactly what I was looking for and even stumbled on your lambda-rollbar first. 

Been spending some time reviewing what everything does and came across one issue and one question:
1) What is `serverless.js` used for and when does it even get used?
2) When I add the config and then deploy I get the error `Invalid characters in environment variable 0`

It seems to be not liking the serverless.yml line where you import the config file using `<<<:`
I figured that what `serverless.js` was for since it looks like that is somehow wrapping the call with yaml-booster. However, don't see anywhere that its being run/used.

**UPDATE**
I now read thru the readme for `yaml-boost` and understand what is happening.

However, it doesn't seem to be working anymore. When I run `sls print -s dev -r us-east-1`
I see this in the output...
```
provider:
  stage: dev
  region: us-east-1
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  timeout: 300
  versionFunctions: false
  environment:
    '0': $
    '1': '{'
    '2': f
    '3': i
    '4': l
    '5': e
    '6': (
    '7': .
    '8': /
    '9': c
    '10': o
    '11': 'n'
    '12': f
    '13': i
    '14': g
    '15': /
    '16': $
    '17': '{'
    '18': o
    '19': p
    '20': t
    '21': ':'
    '22': s
    '23': t
    '24': a
    '25': g
    '26': e
    '27': '}'
    '28': .
    '29': 'y'
    '30': m
    '31': l
    '32': )
    '33': '}'
```

**Comment by simlu** [comment]
We still use this heavily in production. However I haven't deployed this in a while.

I'm currently going through and updating dependencies for this project. So expect an update shortly (it shouldn't really change functionality).

Also, when testing make sure you follow the readme to the letter. My colleague will be replying shortly wrt your issue.

**Comment by MacMcIrish** [comment]
@iDVB 
The `serverless.js` file is used in lieu of the `serverless.yml` file for a top level config that `serverless` uses. `yaml-boost` takes advantage of the fact that the config can be exported as an object, and aggregates other `yml` files to build this object.

The reason your `environment` variables got "stretched out" like they are is that `yaml-boost` doesn't recognize the `-s` flag the same way serverless does. If you try the verbose flags, you should see something different: `sls print --stage dev --region us-east-1`

**Comment by simlu** [comment]
I've started updating the dependencies (they're on the dev branch) - we're currently testing.

However I need to do more work on this project. So expect more updates later and in the coming days/weeks - the project is perfectly usable as it is though.

**Comment by iDVB** [comment]
@MacMcIrish Thanks! that did the trick!

How are you guys finding this `lambda-monitor` working for you?
Currently, everything we deploy is serverless front to back but we've yet to setup any active log/error monitoring, archiving, notifying .

We're currently investigating DataDog, Splunk and Rollbar for this.  Just curious if you have any incite.
